Models/Amiibo.cs
namespace AmiiboTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Amiibo")]
    public partial class Amiibo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amiibo()
        {
            AmiiboUserBridges = new HashSet<AmiiboUserBridge>();
        }

        [Key]
        public int PK { get; set; }

        [Required]
        [StringLength(128)]
        public string AmiiboSeries { get; set; }

        [Required]
        [StringLength(128)]
        public string Character { get; set; }

        [Required]
        [StringLength(128)]
        public string GameSeries { get; set; }

        [Required]
        [StringLength(128)]
        public string Head { get; set; }

        [Required]
        [StringLength(128)]
        public string Image { get; set; }

        [Required]
        [StringLength(128)]
        public string Name { get; set; }


        [StringLength(128)]
        public string ReleaseAU { get; set; }


        [StringLength(128)]
        public string ReleaseEU { get; set; }

        [StringLength(128)]
        public string ReleaseJP { get; set; }


        [StringLength(128)]
        public string ReleaseNA { get; set; }

        [Required]
        [StringLength(128)]
        public string Tail { get; set; }

        [Required]
        [StringLength(128)]
        public string Type { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmiiboUserBridge> AmiiboUserBridges { get; set; }
    }
}

Controllers/AmiiboUserBridgeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmiiboTracker.DAL;
using AmiiboTracker.Models;

namespace AmiiboTracker.Controllers
{
    public class AmiiboUserBridgeController : Controller
    {
        private AmiiboContext db = new AmiiboContext();

        private AmiiboUserBridge bridgeTable = new AmiiboUserBridge();

        // GET: AmiiboUserBridge

        public void AddToWishList(int amiiboID)
        {
            if (!ControllerContext.IsChildAction)
            {
                var userID = db.AspNetUsers.FirstOrDefault(x => x.Email == System.Web.HttpContext.Current.User.Identity.Name).Id;
                Amiibo amiibo2Save = db.Amiiboes.FirstOrDefault(y => y.PK == amiiboID);

                var sameRecord = db.AmiiboUserBridges.Any(x => x.IsWishList == true && x.UserID == userID && x.AmiiboID == amiibo2Save.PK);

                if (sameRecord == false)
                {
                    bridgeTable.AmiiboID = amiibo2Save.PK;
                    bridgeTable.UserID = userID;

                    bridgeTable.IsWishList = true;

                    db.AmiiboUserBridges.Add(bridgeTable);

                    db.SaveChanges();
                }


            }
 
        }

        public void RemoveFromWishList(int amiiboID)
        {
            if (!ControllerContext.IsChildAction)
            {

                var userID = db.AspNetUsers.FirstOrDefault(x => x.Email == System.Web.HttpContext.Current.User.Identity.Name).Id;
                Amiibo amiibo2Save = db.Amiiboes.FirstOrDefault(y => y.PK == amiiboID);

                var sameRecord = db.AmiiboUserBridges.Any(x => x.IsWishList == true && x.UserID == userID && x.AmiiboID == amiibo2Save.PK);

                if (sameRecord == true)
                {
                    var sameRecord2 = db.AmiiboUserBridges.Where(x => x.IsWishList == true && x.UserID == userID && x.AmiiboID == amiibo2Save.PK).FirstOrDefault();

                    db.AmiiboUserBridges.Remove(sameRecord2);

                    db.SaveChanges();
                }
            }

        }

        [Authorize]
        public ActionResult Index()
        {
            var amiiboUserBridges = db.AmiiboUserBridges.Include(a => a.Amiibo).Include(a => a.AspNetUser);
            return View(amiiboUserBridges.ToList());
        }

        // GET: AmiiboUserBridge/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmiiboUserBridge amiiboUserBridge = db.AmiiboUserBridges.Find(id);
            if (amiiboUserBridge == null)
            {
                return HttpNotFound();
            }
            return View(amiiboUserBridge);
        }

        // GET: AmiiboUserBridge/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.AmiiboID = new SelectList(db.Amiiboes, "PK", "AmiiboSeries");
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: AmiiboUserBridge/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PK,UserID,AmiiboID,IsWishList")] AmiiboUserBridge amiiboUserBridge)
        {
            if (ModelState.IsValid)
            {
                db.AmiiboUserBridges.Add(amiiboUserBridge);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AmiiboID = new SelectList(db.Amiiboes, "PK", "AmiiboSeries", amiiboUserBridge.AmiiboID);
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", amiiboUserBridge.UserID);
            return View(amiiboUserBridge);
        }

        // GET: AmiiboUserBridge/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmiiboUserBridge amiiboUserBridge = db.AmiiboUserBridges.Find(id);
            if (amiiboUserBridge == null)
            {
                return HttpNotFound();
            }
            ViewBag.AmiiboID = new SelectList(db.Amiiboes, "PK", "AmiiboSeries", amiiboUserBridge.AmiiboID);
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", amiiboUserBridge.UserID);
            return View(amiiboUserBridge);
        }

        // POST: AmiiboUserBridge/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PK,UserID,AmiiboID,IsWishList")] AmiiboUserBridge amiiboUserBridge)
        {
            if (ModelState.IsValid)
            {
                db.Entry(amiiboUserBridge).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AmiiboID = new SelectList(db.Amiiboes, "PK", "AmiiboSeries", amiiboUserBridge.AmiiboID);
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", amiiboUserBridge.UserID);
            return View(amiiboUserBridge);
        }

        // GET: AmiiboUserBridge/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmiiboUserBridge amiiboUserBridge = db.AmiiboUserBridges.Find(id);
            if (amiiboUserBridge == null)
            {
                return HttpNotFound();
            }
            return View(amiiboUserBridge);
        }

        // POST: AmiiboUserBridge/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AmiiboUserBridge amiiboUserBridge = db.AmiiboUserBridges.Find(id);
            db.AmiiboUserBridges.Remove(amiiboUserBridge);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/AmiibosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmiiboTracker.DAL;
using AmiiboTracker.Models;
using PagedList; 

namespace AmiiboTracker.Controllers
{
    public class AmiibosController : Controller
    {
        private AmiiboContext db = new AmiiboContext();

        // GET: Amiibos

        [Authorize]
        [HttpGet]
        public ActionResult Index(string searchString, string sortOrder, int? page, string currentFilter)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var amiibos1 = from s in db.Amiiboes
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                amiibos1 = amiibos1.Where(s => s.Character.Contains(searchString));
            }

            else
            {
                searchString = currentFilter;
            }



            switch (sortOrder)
            {
                case "name_desc":
                    amiibos1 = amiibos1.OrderBy(s => s.PK);
                    break;
                case "Date":
                    amiibos1 = amiibos1.OrderBy(s => s.PK);
                    break;
                case "date_desc":
                    amiibos1 = amiibos1.OrderBy(s => s.PK);
                    break;
                default:  // Name ascending 
                    amiibos1 = amiibos1.OrderBy(s => s.PK);
                    break;
            }




            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ViewBag.itemCount = amiibos1.Count(); 
            return View(amiibos1.ToPagedList(pageNumber, pageSize));

            //return View(db.Amiiboes.ToList());
        }



        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Amiibo amiibo = db.Amiiboes.Find(id);
            if (amiibo == null)
            {
                return HttpNotFound();
            }
            return View(amiibo);
        }

        // POST: Amiibos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PK,AmiiboSeries,Character,GameSeries,Head,Image,Name,ReleaseAU,ReleaseEU,ReleaseJP,ReleaseNA,Tail,Type")] Amiibo amiibo)
        {
            if (ModelState.IsValid)
            {
                db.Amiiboes.Add(amiibo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(amiibo);
        }

        [Authorize]
        // GET: Amiibos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Amiibo amiibo = db.Amiiboes.Find(id);
            if (amiibo == null)
            {
                return HttpNotFound();
            }
            return View(amiibo);
        }

        // POST: Amiibos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PK,AmiiboSeries,Character,GameSeries,Head,Image,Name,ReleaseAU,ReleaseEU,ReleaseJP,ReleaseNA,Tail,Type")] Amiibo amiibo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(amiibo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(amiibo);
        }

        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Amiibo amiibo = db.Amiiboes.Find(id);
            if (amiibo == null)
            {
                return HttpNotFound();
            }
            return View(amiibo);
        }

        // POST: Amiibos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Amiibo amiibo = db.Amiiboes.Find(id);
            db.Amiiboes.Remove(amiibo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Amiibos/Create.cshtml
@model AmiiboTracker.Models.Amiibo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Amiibo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AmiiboSeries, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmiiboSeries, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmiiboSeries, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Character, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Character, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Character, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GameSeries, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GameSeries, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GameSeries, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Head, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Head, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Head, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseAU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseAU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseAU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseEU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseEU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseEU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseJP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseJP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseJP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseNA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseNA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseNA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Amiibos/Delete.cshtml
@model AmiiboTracker.Models.Amiibo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Amiibo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AmiiboSeries)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmiiboSeries)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Character)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Character)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GameSeries)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GameSeries)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Head)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Head)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseAU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseAU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseEU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseEU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseJP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseJP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseNA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseNA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Amiibos/Index.cshtml
@model PagedList.IPagedList<AmiiboTracker.Models.Amiibo>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=BioRhyme&display=swap" rel="stylesheet">
<link rel="stylesheet" href="//code.jquery.com/ui/1.8.10/themes/smoothness/jquery-ui.css" type="text/css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

<body>
    <div class="row" id="nav-link-row">
        <div class="col-sm-3" id="amiiboLink">
            <div class="row">
                <img src="https://i.postimg.cc/25SLs3rN/kirb.png" style="width:150px ; height: 150px">
            </div>
            <div class="row" id="amiiboLink">
                @Html.ActionLink("All Amiibos", "Index")
            </div>
        </div>
        <div class="col-sm-3" id="amiiboLink">
            <div class="row">
                <img src="https://i.postimg.cc/vB1gmj4P/sable.png" style="width:150px ; height: 150px">
            </div>
            <div class="row" id="amiiboLink">
                @Html.ActionLink("My Amiibos", "Index", "AmiiboUserBridge")
            </div>

        </div>
        <div class="col-sm-3" id="amiiboLink">
            <div class="row">
                <img src="https://i.postimg.cc/q7D640vh/shovel.png" style="width:150px ; height: 150px">
            </div>
            <div class="row" id="amiiboLink">
                @Html.ActionLink("My Wishlist", "Index", "AmiiboUserBridge")
            </div>
        </div>
    </div>

    @using (Html.BeginForm("Index", "Amiibos", FormMethod.Get))
    {
        <p style="float: right; margin-left: 20px; font-size: 20px; padding-top: 80px; font-weight: bold; padding-right: 30px;">
            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" style="max-width: 480px;
        max-height: 100px;
        font-size: 22px;
        border-radius: 5px;
        background-color: #e27d5f ;
        text-decoration: none ;
        border: none ;
" />
        </p>
    }

    <table class="table" border="0" id="searchTable">
        @for (int i = 0; i < Model.Count; i += 2)
        {

            <tr id="amiiboRow">
                <td id="amiiboCol1" style="border-radius: 20px; width: 500px ;">
                    <img src="@(Model[i].Image)" style="width: 250px ; height: 300px ; " />
                    <hr style="height: 5px" />
                    <p id="amiiboName" style="font-size: 40px">@Model[i].Name</p>
                    <p id="amiiboSeries" style="font-size: 25px">@Model[i].GameSeries</p>

                    @if (Model[i].ReleaseAU != null)
                    {
                        <p id="releaseDate">Austrailia Release: @Model[i].ReleaseAU</p>
                    }

                    @if (Model[i].ReleaseNA != null)
                    {
                        <p id="releaseDate">USA Release: @Model[i].ReleaseNA</p>
                    }
                    @if (Model[i].ReleaseEU != null)
                    {
                        <p id="releaseDate">Europe Release: @Model[i].ReleaseEU</p>
                    }
                    @if (Model[i].ReleaseJP != null)
                    {
                        <p id="releaseDate">Japan Release: @Model[i].ReleaseJP</p>
                    }

                    <div class="row" id="addRow">
                        <div class="col" style="width: 150px ;">
                            <button type="button" id="haveButton"><i class="far fa-check-circle"></i></button><p>I Have This</p>
                        </div>
                        <div class="col" style="width: 150px ;">
                            <button type="button" class="wishButton" value="@Model[i].PK" data-instance="@i">
                                <i  id="wish_@i" class="far fa-heart"></i>
                            </button><p>I Want This</p>
                        </div>
                    </div>

                </td>

                @if ((i + 1) < Model.Count())
                {
                    <td id="amiiboCol2" style="border-radius: 20px; width: 500px ;">
                        <img src="@(Model[i+1].Image)" style="width: 250px ; height: 300px ; " />
                        <hr />
                        <p id="amiiboName" style="font-size: 40px">@Model[i + 1].Name</p>
                        <p id="amiiboSeries" style="font-size: 25px">@Model[i + 1].GameSeries</p>

                        @if (Model[i + 1].ReleaseAU != null)
                        {
                            <p id="releaseDate">Austrailia Release: @Model[i + 1].ReleaseAU</p>
                        }

                        @if (Model[i + 1].ReleaseNA != null)
                        {
                            <p id="releaseDate">USA Release: @Model[i + 1].ReleaseNA</p>
                        }

                        @if (Model[i + 1].ReleaseEU != null)
                        {
                            <p id="releaseDate">Europe Release: @Model[i + 1].ReleaseEU</p>
                        }
                        @if (Model[i + 1].ReleaseJP != null)
                        {
                            <p id="releaseDate">Japan Release: @Model[i + 1].ReleaseJP</p>
                        }


                        <div class="row" id="addRow">
                            <div class="col" style="width: 150px ;">
                                <button type="button" id="haveButton"><i class="material-icons md-48">face</i></button><p>I Have This</p>
                            </div>
                            <div class="col" style="width: 150px ;">
                                <button type="button" class="wishButton2" value="@Model[i + 1].PK">
                                    <i id="wish_@(i+1)" class="far fa-heart"></i>
                                </button><p>I Want This</p>
                            </div>
                        </div>



                    </td>
                }

            </tr>
        }
    </table>

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/js/all.min.js"
        integrity="sha512-YSdqvJoZr83hj76AIVdOcvLWYMWzy6sJyIMic2aQz5kh2bPTd9dzY3NtdeEAzPp/PhgZqr4aJObB3ym/vsItMg=="
        crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>


<script>
    $('.wishButton').click(function (e) {

        e.preventDefault();

        var selectedId = $(this).val();

        var num2find = $(this).data().data; 

        var id2find = "wish_" + num2find; 

        var temp2 = parseInt(num2find); 

        var temp = document.getElementById(id2find);




        $.ajax({
            url: "/AmiiboUserBridge/AddToWishList",
            type: "POST",
            data: { amiiboId: selectedId },
            success: function (data) {

                //console.log(data);

                console.log(selectedId);
                

            },
            error: function () {
                alert("An error has occured!!!");
            }
        });
    });

    $('.wishButton2').click(function (e) {

        e.preventDefault();

        var selectedId = $(this).val();

        $.ajax({
            url: "/AmiiboUserBridge/AddToWishList",
            type: "POST",
            data: { amiiboId: selectedId },
            success: function (data) {
                if (data.status == "Success") {
                    alert("Done");
                }
            },
            error: function () {
                alert("An error has occured!!!");
            }
        });
    });
</script>